server:
  port: 9003

spring:
  application:
    name: mutual-service
  cloud:
    loadbalancer:
      ribbon: 
        enabled: false
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
      auto-commit: false
    url: ${DB_URL:jdbc:postgresql://localhost:5432/kicau_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
            
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 600000 #10 mins
        readTimeout: 600000 #10 mins

security:
  jwt:
    secret: 12345